# 6章オブジェクト指向プログラミング
## 西野泰平

### 6.1 Pythonオブジェクトのオフジェクト指向

#### int

##### 単純な整数オブジェクト。このような基本的なPythonオブジェクトでも主なOOP機能があります。

In [111]:
#新たなインスタンスn(1行目)
#オブジェクトの型(2行目)
n = 5
type(n)

int

In [112]:
#属性
n.numerator

5

In [113]:
#メソッド
n.bit_length() 

3

In [114]:
#＋演算子（和）適用
n + n

10

In [115]:
#＊演算子（積）適用
2 * n

10

In [116]:
#特殊メソッド__sizeof__()でメモリ使用量（バイト）
n.__sizeof__()

28

#### list

##### listオブジェクトのメソッドは数が多いですが基本的に同じように振る舞います。

In [117]:
#新インスタンスl(1行目)
#オブジェクトの型(2行目)
l = [1, 2, 3, 4]
type(l)


list

In [118]:
#インデックスで要素を選択
l[0]

1

In [119]:
#メソッド(1行目)
#＋演算子（連結）適用(2行目)
l.append(10)
l + l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [120]:
#＊演算子（連結）適用
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [121]:
#標準Python関数sum()適用
sum(l)

20

In [122]:
#特殊メソッド__sizeof__()でメモリ使用量（バイト）
l.__sizeof__()

104

#### ndarray

##### intとlistは標準Pythonオブジェクトです。NumPyのndarrayオブジェクトはオープンソースパッケージの「カスタムメイド」オブジェクトです。

In [123]:
import numpy as np

In [124]:
#新インスタンスa
a=np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
#オブジェクトの型
type(a)

numpy.ndarray

##### ndarrayオブジェクトは、Pythonの標準的なオブジェクトとは異なる特徴を持っています。本章の後で述べるPythonデータモデルのおかげで多くの場合に標準オブジェクトのように振る舞います。

In [126]:
#属性
a.nbytes

64

In [127]:
#メソッド（集約）
a.sum()

120

In [128]:
#メソッド（非集約）
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [129]:
#＋演算子（和）適用
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [130]:
#＊演算子（積）適用
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [131]:
#標準Python関数sum()適用
sum(a)

array([24, 28, 32, 36])

In [132]:
#NumPyユニバーサル関数np.sum()適用
np.sum(a)

120

In [133]:
#特殊メソッド__sizeof__()でメモリ使用量（バイト）
a.__sizeof__()


128

#### DataFrame

##### pandasの DataFrameオブジェクトはndarrayオブジェクトと同じように振る舞います。まず、ndarrayオブジェクトによるDataFrameオブジェクトのインスタンス化です。

In [134]:
import pandas as pd

In [135]:
#新インスタンスdf(1行目)
#オブジェクトの型(2行目)
df = pd.DataFrame(a,columns=list('abcd'))
type(df)

pandas.core.frame.DataFrame

In [136]:
#属性
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [137]:
#メソッド(集約)
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [138]:
#メソッド（非集約）
df.cumsum() 


a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [139]:
#＋演算子（和）適用
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [140]:
#＊演算子（積）適用
2 * df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [141]:
#NumPyユニバーサル関数np.sum()適用
np.sum(df)

a    24
b    28
c    32
d    36
dtype: int64

In [142]:
#特殊メソッド__sizeof__()でメモリ使用量（バイト）
df.__sizeof__()

196

### 6.2 Pythonクラスの基本

##### PythonでOOPを使う主要概念と具体的な構文を述べました。次に、既存のPythonオブジェクト型では簡単に、効率的に、適切にモデル化できないオブジェクトをモデル化するカスタムクラスの作成を扱います。ここからは、金融商品を題材としてPythonクラスについて考えていきます。

In [143]:
#クラス定義(1行目)
#コード、この場合はpassキーワードだけ。(2行目)
class Financialinstrument (object):
    pass

In [144]:
#クラスの新インスタンスfi(1行目)
#オブジェクトの型(2行目)
fi = Financialinstrument()
type(fi)

__main__.Financialinstrument

In [145]:
#どのPythonオブジェクトにも (object由来の）「特殊」属性とメソッドがある。文字列表現を検索する特殊メソッド呼び出し。
fi

In [146]:
fi.__str__()

'<__main__.Financialinstrument object at 0x00000123F3141C50>'

In [147]:
#通常の属性とは異なる、いわゆるテータ属性がどのオブジェクトでも定義される。
fi.price = 100
fi.price

100

##### 重要な特殊メソッドがインスタンス化で呼び出される__init__です。オブジェクトそのもの(表記はself)とオプションで複数の引数を取ります。

In [148]:
#クラス属性（全インスタンスが継承）定義(2行目)
#初期化で呼び出される特殊メソッド＿＿init＿＿()を定義(3行目)
#（インスタンスごとの）インスタンス属性を定義(4行目、5行目)
class FinancialInstrument(object):
    author='Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price

In [149]:
FinancialInstrument.author

'Yves Hilpisch'

In [150]:
#新インスタンス、aapl(1行目)
aapl = FinancialInstrument('AAPL', 100)

In [151]:
#インスタンス属性にアクセス
aapl.symbol

'AAPL'

In [152]:
#クラス属性にアクセス
aapl.author

'Yves Hilpisch'

In [153]:
#インスタンス属性の値を変更
aapl.price = 105
aapl.price

105

##### 金融商品の値段は常に変わりますが、金融商品のシンボルはあまり変わりません。クラス定義のカプセル化のために 2つのメソッド、get_price()とset_price()を定義します。次のコードは (objectからでなく)前のクラス定義を継承しています。

In [154]:
#前のバージョンを継承したクラス定義(1行目)
#get_price()メソッド定義(2行目、3行目)
#set_price()メソッド定義(4行目)
#引数値でインスタンス属性値更新(5行目)
class FinancialInstrument(Financialinstrument): 
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [155]:
#新クラス定義による新インスタンス、fi(1行目)
#get_price()メソッド呼び出しでインスタンス属性値検索(2行目)
fi = FinancialInstrument('AAPL',100)
fi.get_price()

TypeError: FinancialInstrument() takes no arguments

In [156]:
#set_price(）でインスタンス属性値更新
fi.set_price(105)

AttributeError: 'Financialinstrument' object has no attribute 'set_price'

In [157]:
fi.get_price()

AttributeError: 'Financialinstrument' object has no attribute 'get_price'

In [158]:
#インスタンス属性に直接アクセス
fi.price

100

##### カプセル化の目的はクラスを扱うユーザからデータを隠蔽することです。getter/setterメソッドの追加はそのためのものです。しかし、これでは、ユーザによるインスタンス属性の直接アクセス／更新を防げません。そこでプライベートインスタンス属性の登場です。先頭の 2つのアンダースコアで定義します。

In [159]:
#プライベートインスタンス属性の値段を定義(4行目)
class FinancialInstrument(object): 
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price
        def get_price(self):
            return self.__price
        def set_price(self, price):
            self.__price = price


In [160]:
#メソッドget_price()は値を返す(2行目)
fi = FinancialInstrument('AAPL', 100)
fi.get_price()

AttributeError: 'FinancialInstrument' object has no attribute 'get_price'

In [161]:
#属性に直接アクセスするとエラーを起こす
fi.__price

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [162]:
#クラス名の先頭が下線だと直接アクセス／更新が可能
fi._FinancialInstrument__price

100

In [163]:
fi._Financialinstrument__price = 105

In [164]:
#値段を元の値に戻す
fi.set_price(100)

AttributeError: 'FinancialInstrument' object has no attribute 'set_price'

##### 金融商品のポートフォリオのポジションをモデル化する別のクラスを考えます。2つのクラスの集約は概念としてはわかりやすいものです。PortfolioPositionクラスのインスタンスが属性値にFinancialInstrumentクラスのインスタンスを取ります。position_sizeのようなインスタンス属性を追加して、例えば時価を計算できます。

In [165]:
#FinancialInstrumentクラスのインスタンスに基づくインスタンス属性(3行目)
#PortfolioPositionクラスのプライベートインスタンス属性(4行目)
#属性に基づく時価計算(11行目)
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
        def get_position_size(self):
            return self.__position_size
            def update_position_size(self, position_size):
                self.__position_size = position_size
                def get_position_value(self):
                    return self.__position_size * \
                        self.position.get_price()

In [166]:
pp = PortfolioPosition(fi, 10)

In [167]:
pp.get_position_size()

AttributeError: 'PortfolioPosition' object has no attribute 'get_position_size'

In [168]:
pp.get_position_value()

AttributeError: 'PortfolioPosition' object has no attribute 'get_position_value'

In [169]:
#インスタンス属性オプジェクトのメソッドは直接アクセスもできる(隠蔽も可)
pp.position.get_price()

AttributeError: 'FinancialInstrument' object has no attribute 'get_price'

In [170]:
#金融商品の値段更新
pp.position.set_price(105)

AttributeError: 'FinancialInstrument' object has no attribute 'set_price'

In [171]:
#更新された値段に基づき新たな時価計算
pp.get_position_value() 

AttributeError: 'PortfolioPosition' object has no attribute 'get_position_value'

### 6.3 Pythonのデータモデル

##### これまでの例は、いわゆるPythonテータすなわちオフジェクトモデル (https:// docs.python.org/ ja/3/ reference/ datamodel.html)のいくつかの側面を示してきました。PythonデータモデルによりPythonの基本言語要素に沿ったクラスを設計できます。
##### Pythonデータモデルは非常に重要なので、Ramalho(2015)の例を少し手直ししていくつかの側面を検討します。（ユークリッド空間のベクトルのような）1次元3要素ベクトルのクラスを実装します。まず特殊メソッド__init__です。

In [172]:
#あらかじめ初期化したインスタンス属性(3次元空間を考える）(2~5行目)
class Vector(object):
    def __init__(self, x=0, y=0,z=0):
        self.x = x
        self.y = y
        self.z = z

In [173]:
#新インスタンスv(1行目)
#デフォルトの文字列表現(2行目)
v = Vector(1, 2, 3)
v

##### オブジェクトを説明する文字列表現は特殊メソッド__repr__で可能です。

In [174]:
class Vector(Vector): 
    def __repr__(self): 
        return'Vector(%r, %r, %r)'% (self.x, self.y, self.z)

In [175]:
#新たな文字列表現
v = Vector(1, 2, 3)
v

Vector(1, 2, 3)

In [176]:
print(v)

Vector(1, 2, 3)


##### 標準Python関数abs()とbool()のVectorクラスにおける振る舞いは特殊メソッド__abs__と__bool__で定義できます。

In [177]:
#3属性値のユーク リッド・ノルムを返す(3行目)
class Vector(Vector): 
    def __abs__(self): 
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
        def __bool__(self) : return bool(abs(self))

In [178]:
#非ゼロ属性値の新Vectorオブジェクト
v = Vector(1, 2, -1)
abs(v)

2.449489742783178

In [179]:
abs(v)

2.449489742783178

In [180]:
bool(v)

True

In [181]:
#ゼロ属性値だけの新Vectorオブジェクト
V = Vector()
V


Vector(0, 0, 0)

In [182]:
abs(V)

0.0

In [183]:
bool(V)

True

##### 何度も示したように、＋と＊演算子はほとんどのPythonオブジェクトに使えます。それらの振る舞いは特殊メソッド__add__と__mul__で定義されます。

In [184]:
#この場合、特殊メソッドは、同じ種類のオプジェクトを返す
class Vector(Vector): 
    def __add__(self, other): 
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
        def __mul__(self, scalar): 
            return Vector(self.x * scalar, 
            self.y * scalar, 
            self. z * scalar)

In [185]:
v = Vector(1, 2, 3) 

In [186]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [187]:
v * 2

TypeError: unsupported operand type(s) for *: 'Vector' and 'int'

##### 別の標準 Python関数len()は、オブジェクトの要素数の長さを返します。関数は呼び出されると、特殊メソッド__len__にアクセスします。特殊メソッド__getitem__は、角括弧表記のインデックス操作を行います。

In [188]:
#Vectorクラスの全インスタンスは長さが3
class Vector(Vector): 
    def __len__(self) : return 3
    def __getitem__(self, i) : 
        if i in [0, -3]: return self.x 
        elif i in [1, -2]: return self.y 
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [189]:
v = Vector(1, 2, 3)
len(v)

3

In [190]:
v[0]

1

In [191]:
v[-2]

2

In [192]:
v[3]

IndexError: Index out of range.

##### 特殊メソッド__iter__はオブジェクトの要素でイテレーションするときの振る舞いを定義します。これが定義されたオブジェクトはイテラブルと呼ばれます。例えば、コレクションとコンテナはすべてイテラブルです。

In [193]:
class Vector(Vector): 
    def __iter__(self): 
        for i in range(len(self)): 
            yield self[i]

In [194]:
v = Vector(1, 2, 3)

In [195]:
#(__getitem__による）インテックスの値を用いた間接イテレーション
for i in range(3):
    print(v[i])

1
2
3


In [196]:
#(__iter__を用いた)クラスのインスタンスの直接イテレーション
for coordinate in v: 
    print(coordinate)

1
2
3


### 6.4 Vectorクラス

##### Vectorのメソッドを示します。

In [197]:
class Vector(object): 
    def __init__(self, X=0, y=0, Z=0): 
        self.x = x 
        self.y = y 
        self.z = z 
        def __repr__(self) : 
            return'Vector(%r, %r, %r)'% (self.x, self.y, self.z)
            def __abs__(self): 
                return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
                def __bool__(self): 
                    return bool(abs(self))
                    def __add__(self, other) : 
                        x = self.x + other.x 
                        y = self.y + other.y 
                        z = self.z + other.z 
                        return Vector(x, y, z)
                        def __mul__(self, scalar): 
                            return Vector(self.x * scalar, self.y * scalar, self.z * scalar)
                            def len (self) : return 3 
                            def __getitem__(self, i):
                                if i in [0, -3]: return self.x 
                                elif i in [1, -2]: return self.y 
                                elif i in [2, -1]: return self. z 
                                else: raise IndexError('Index out of range.')
                                def __iter__(self): 
                                    for i in range(len(self)): 
                                        yield self[i]

### 6.5 結論

##### 本章はオブジェクト指向プログラミング (OOP)の概念と実現方法を理論的ならびにPythonの例を用いて紹介しました。OOPはPythonの主プログラミングパラダイムです。複雑なアプリケーションのモデル化と実装だけでなく柔軟なPythonデータモデルにより、標準Pythonオブジェクトのように振る舞うカスタムオブジェクトが作成できます。OOPには批判 もありますが、Pythonプログラマとクオンツにはある程度の複雑さに達した場合に役立つ強力なツールだと言っても良いでしょう 。「第5部デリハティブ分析」で説明するデリバティブの価格付けパッケージは、OOPが、本質的な複雑さへの対と抽象化への要件を満たす唯一のプログラミングパラダイムであることを示しています。